name: CI

on:
  push:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[auto]: ')"
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup

    steps:
    - name: Checkout Main Repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}

    - name: Setup Basics
      id: user
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm --needed sudo git base-devel go upx
        useradd -m hmkdarfdas
        echo 'hmkdarfdas ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

    - name: Install YAY
      id: yay
      run: |
        su hmkdarfdas <<'EOF'
        _yaydir=$(mktemp -d)
        git clone https://aur.archlinux.org/yay.git ${_yaydir}
        cd ${_yaydir} && makepkg -si --noconfirm
        EOF
      if: steps.user.outcome == 'success'

    - name: Install Build Dependencies
      id: dependencies
      run: |
        su hmkdarfdas <<'EOF'
        rustup target add x86_64-unknown-linux-musl
        yay -S --noconfirm rust-musl musl
        cargo install pyoxidizer
        EOF
      if: steps.yay.outcome == 'success'

    - name: Build
      id: build
      run: |
        su hmkdarfdas <<'EOF'
        _builddir=$(mktemp -d)
        git clone https://github.com/richardk80/spotify-ripper.git ${_builddir}
        cd ${_builddir}
        cp ${GITHUB_WORKSPACE}/pyoxidizer.bzl .
        touch README.rst
        pyoxidizer build --target-triple x86_64-unknown-linux-musl
        find . -executable -type f
        EOF
      if: steps.dependencies.outcome == 'success'
