name: CI

on:
  push:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[auto]: ')"
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup

    steps:
    - name: Checkout Main Repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}

    - name: Setup User Account
      id: user
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm sudo
        useradd -m hmkdarfdas
        echo 'hmkdarfdas ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

    - name: Install YAY
      id: yay
      run: |
        _yaydir=$(mktemp -d)
        pacman -S --noconfirm --needed git base-devel
        git clone https://aur.archlinux.org/yay.git ${_yaydir}
        cd ${_yaydir} && su hmkdarfdas -c 'makepkg -si'
      if: steps.user.outcome == 'success'

    - name: Install Build Dependencies
      id: dependencies
      run: |
        yay -S --noconfirm pyoxidizer
      if: steps.yay.outcome == 'success'
